# Generated by Django 4.2.6 on 2023-10-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('main_text', models.TextField(max_length=500)),
                ('box_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
